name: Multi-module Java CI (Node 14)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout projektu
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Nastaveni JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # 3. Nastaveni Node.js na verzi 14
    - name: Set up Node.js 14
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    # 4. Instalace frontend zavislosti v podmodulu sdnnt
    - name: npm install
      working-directory: ./sdnnt/src/main/ui
      run: npm install

    # 5. Maven build z korene projektu
    # Pouzivame install, aby se 'openapi' modul ulozil do lokalniho repo pro 'sdnnt' modul
    - name: Build with Maven
      run: mvn -B install --file pom.xml

    # 6. Ulozeni vysledneho WAR souboru
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sdnnt-war-package
        path: sdnnt/target/*.war